projects:
  70days:
    schemaPath: amplify/backend/api/70days/build/schema.graphql
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: ap-northeast-2
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
