# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'awsAmplifyTuto (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for awsAmplifyTuto (iOS)
#pod 'AWSAppSync', '~> 2.15.0'

end

target 'awsAmplifyTuto (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for awsAmplifyTuto (macOS)

end
