# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'seventyDays dev' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for seventyDays dev
  pod 'Alamofire', '~> 4.1'
  pod 'AlamofireObjectMapper', '~> 6.0.0'
  pod 'ObjectMapper', '~> 3.4.2'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'Kingfisher', '~> 5.4.0'
  pod 'SwifterSwift', '~> 5.0.0'
  
  pod 'Hero', '1.4.0'
  pod 'arek', '~> 4.0.2'
  
  pod 'ReachabilitySwift', '~> 3'
  pod 'GDPerformanceView-Swift'
end

target 'seventyDays dist' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for seventyDays dist


end
