included:
  - EventsApp

excluded:
  - EventsApp/EventsAPI.swift

# Note: This feature is experimental. As of this writing (4-Dec-2018) warnings
# triggered by these rules should not be used to fail builds. Known issues:
# - unused_private_declaration incorrectly triggers on
#   AWSAppSyncClientConfiguration.oidcAuthProvider
analyzer_rules:
  - unused_import
  - unused_declaration

opt_in_rules:
  - empty_count

# configurable rules can be customized from this configuration file
closing_brace: error
colon:
  severity: error
comma: error
empty_count: warning
empty_enum_arguments: error
function_body_length:
  warning: 100
  error: 150
line_length:
  warning: 120
  error: 160
opening_brace: error
return_arrow_whitespace: error
statement_position:
  severity: error
todo: warning
trailing_semicolon: error
